ontologies:
  source:
    - url: 'https://spec.pistoiaalliance.org/idmp/ontology/MetadataIDMP/'
    - url: 'https://spec.pistoiaalliance.org/idmp/ontology/AboutIDMPDev/'
  catalog_path:
    - ontologies/catalog-v001.xml
  module_ignore_pattern:
    - '^(About|Metadata|Load).*'
    - 'http.*(About|Metadata).*'